name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: 'jinventory'
          POSTGRES_PASSWORD: 'jinventory'
          POSTGRES_USER: 'jinventory'
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: mvn --batch-mode --update-snapshots verify
